### PR TITLE
Feature/i18n Translation to Italian and German

### PR DESCRIPTION
**Pull request by aballaci**
Hi Zen Team,

Let me please know what you think of the feature.

The i18n loads the language for the default Locale of the user if supported otherwise defaults to English,
the language menu stores the preference for the next start sending a message to the user in the current language.

A dynamic repaint of the whole interface is not implemented at the moment because too invasive and a bit tricky.

Send me please feedback and suggestions.

Best regards,
Armand

### CODE REVIEW

**Comment by vaklinov** [comment]
Thank you very much for this feature. I intend to possibly try to integrate it into the wallet later this month. You have indeed done a lot of work on it. However it is not complete:
1. Some classes are not i18n-ed e.g.: SingleKeyImportDialog StartupProgressDialog CreateGroupDialog
2. I think it is better to maintain two versions of the properties files: one to edit locally that is encoded in UTF-8 (for all languages) and another one where all non ASCII chars are encoded \xxxx using native2ascii
3. I also think it is a good idea to let the user choose the language via a menu option (explicitly)
4. Using the JVM preferences API is good but the GUI wallet by design stores user data in ~/.ZENCashSwingWalletUI - so I may wish to change the storage there instead of using java.util.prefs.Preferences... this is a minor issue.

So if you have time, please try to complete it. If not, I will complete it myself. I am grateful that you have made a contribution of this size...

**Comment by aballaci** [comment]
Hi Ivan,

it´s a pleasure to contribute :) I am still working on it and i know there is some work left. I will take care of your suggestions and I guess it will be ready in the next week or so. I have intentionally left a couple of triky things that maybe need your attention.

1. the not i18n classes will be read asap
2. I don´t quite get the idea, could you please give me an example? ( by the way you are welcome to change it directly in the branch)
3. the Language selection menu is already implemented, it requires a interface restart to take the changes. a full interface repaint looks a bit invasive. Do you have any implementation idea?
4. i will follow the current implementation for storing preferences

Thanky you for the suggestions, I´m always happy to help.

**Comment by vaklinov** [comment]
Hi Armand,
  Likewise thank you. Please take your time - all of this is not urgent. About some individual points:

2. The current files of type:
src/resources/messages/zencash_xx.properties
need to be encoded in ISO-8869-1 (Java requirement). This is fine for manual editing for the major European languages but will not be OK for others later on. So I think we could maintain two copies per file:
2.1. src/resources/messages/zencash_xx.properties - to be used at runtime (encoded via native2ascii in ISO-8869-1)
2.2. src/resources/messages/zencash_xx_editable.properties - to be used for manual editing and have UTF-8 encoding.
3. You are right - I failed to see the full implementation.

**Comment by aballaci** [comment]
Hi Ivan,
I was thinking of splitting this story in two parts:

First, 
- string externalisation only.
- in the next step the language selection and properties translation. 

This way we can take care of the points you mentioned, like native2ascii and UTF8 encoding, merge early and have a clean translation review process wchich can last a little bit. Let me please know what you think.
Best regards,
Armand

**Comment by vaklinov** [comment]
Hi Armand,
   Yes, I agree. Thank you.

Before I start the actual review and merge of this PR, I intend to merge one other feature into the Git master branch (address labels) and make a new release. This will take me 1 week+.

**Comment by vaklinov** [comment]
Tomorrow I shall start reviewing and integrating the pull request. Due to the large number of changes and some conflicts, a direct merge is not possible. Instead I will merge manually into a branch of my own - little by little. Clearly it is not "finished" but I wish to thank you for the work done so far...

**Comment by aballaci** [comment]
Sounds good, I have removed the extra lang properties and the menu language selection, the langutil gets the defauld Lokale.US

**Comment by aballaci** [comment]
Would be nice if my contribution remains visible

**Comment by vaklinov** [comment]
OK. I also wish to have your contribution visible and I would like you to get the credit and recognition for it. So I will try to merge the pull request directly... after a review.

**Comment by vaklinov** [comment]
What is the origin of the images (national flags). Do they come with some copyright/license?

**Comment by aballaci** [comment]
Cool, the images come with no copyright/license restrictions...

**Comment by vaklinov** [comment]
My review of this PR feature is OK. It will be merged. 

Regarding images: Indeed since they come with come with no copyright/license restrictions we can use them. Could you point to the Internet source where they were taken from? It is a good idea to know the source of such external content, and we will also need more flag images later on.

**Pull request merged**
