### PR TITLE
Feature: zend command line parameters

### PR DESCRIPTION
**Pull request by zenportodev**
This feature makes it possible for the GUI wallet to start zend with custom parameters. A new menu option is created: `Wallet >> Edit zend parameters` for it. The parameters are stored in a configuration file `zend-cmd-options.conf` that may be edited via the GUI or (in emergencies) with an text editor.

GUI editing dialog:
params_edit

If anyone wishes to try this feature without building from source, they may take the latest official wallet release and only replaced the ZENCashSwingWalletUI.jar with the one attached here (it is zipped):
[ZENCashSwingWalletUI.jar.zipped.zip](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/files/2280353/ZENCashSwingWalletUI.jar.zipped.zip)

### CODE REVIEW

**Comment by tarrenj** [comment]
Assigned @zennermac to help with testing since I'll be AFK shortly.

**Comment by zenportodev** [comment]
@tarrenj This feature is a fresh/clean implementation. There is no code copy/pasted from the other similar PR. There is thus no possibility of cherry-picking commits.

**Comment by tarrenj** [comment]
@zenportodev ACK, thanks for clarifying.  I'll try to test/review later tonight, but no promises.

**Comment by tarrenj** [comment]
Minor NIT: The `Edit zend parameters...` window appends 5 empty lines to the file whenever it opens.

**Comment by tarrenj** [comment]
If we merge this, we can close #110.

**Comment by zenportodev** [comment]
@tarrenj Thank you very much for your tests. If there are no further objections by others I will merge the pull request within a few days.

Some comment on the issues reported:

1. `The Edit zend parameters... window dialog appends 5 empty lines to the file ...` I do not think this is the case. The UI window text areas has a few empty lines if the current number of options is below 5, but this is just for aesthetics. The file `zend-cmd-options.conf` does not get extra 5 lines... I think.
1. `Does not save this long string: #START...`  The format of file `zend-cmd-options.conf` is that lines starting with # are comments (not loaded as parameters). If the user adds lines starting with # in the GUI they are also ignored. Only the actual parameters are saved in the file...
1. `The window defaults to a size that does not show the full content:` - This issue is not related to the current feature. The current feature does not change the main Windows sizing. This occurs on Windows systems when (typically on large displays) elements are scaled 1x-2x via the Windows settings. We have to do a better job of detecting this and calculating the Window size then... a point to be fixed some day.

**Comment by tarrenj** [comment]
@zenportodev You're right on all accounts.

**Pull request merged**
