### PR TITLE
Feature/advanced settings

### PR DESCRIPTION
**Pull request by josephnicholas**
**Swing Wallet Advanced Settings Feature:**
This feature will be used to add some additional commands/option to the zen daemon during startup. Right now the the commands/options are written in a separate file called _commands.conf_, if this file has commands/options then it will be added to the zen daemon launch, and if its empty a normal launch will be processed.

Currently a manual restart will be the only way to apply the changes, but we are making a automated restart functionality to ease user interaction, hopefully in the next release.

### CODE REVIEW

**Comment by zenportodev** [comment]
Some initial notes:

The file commands.conf is created as:
`File commandsFile = new File("commands.conf");`
This palces it in the current directory, which may be different depending on OS type and installation… If the intention is for this to be a permanent config file, it is better to place it in the wallet config setting directory: `OSUtil.getSettingsDirectory();`

Upon first start when this file is missing, there is an exception in the log:
```
java.io.FileNotFoundException: commands.conf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.vaklinov.zcashui.StartupProgressDialog.readAndShowProcess(StartupProgressDialog.java:278)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:121)
	at com.vaklinov.zcashui.ZcashUI.main(ZCashUI.java:741)
```
It is a good practice to check if the file exists before trying to read it.

When the user configures custom options, the file commands.conf is read and used but then it is intentionally emtied! Is this intended? This means that if the user sets the options they are not remembered and will be used only once on the next restart – and then they will be lost. IMHO most users will think of this as a bug.

When the file is emptied the code pattern is:
```
        try (FileInputStream streamReadCommands = new FileInputStream(commandsFile)) {

...

            Log.info("Emptying commands.conf");
            PrintWriter pw = new PrintWriter(commandsFile);
            pw.print("");
            pw.close();
}
```
At the point of being emptied the  file is still open as a FileInputStream. Emptying it by opening it a second time (without closing the FileInputStream) may potentially cause issues on some OSes etc. It seems to work so this is only a “potential problem”.

**Comment by josephnicholas** [comment]
@zenportodev I have refactored the code based on some of your provided suggestions. Please do review it again.

For the topic on emptying the config, I think it is needed to empty the file just to avoid adding the option during every restart, which creates a confusion. How about, we empty the file, but then we still show it on the user on the Advanced settings panel, so that the user has the idea on what was applied previously. What do you think?

**Comment by zenportodev** [comment]
The latest code changes look OK to me. 

Regarding 
`For the topic on emptying the config, I think it is needed to empty the file just to avoid adding the option during every restart, which creates a confusion.`
I do not fully understand your intention here - let us consider what users want. A user (I believe) expects to set options to zend which will be used to start zend every time the wallet is started. If the commands.conf file is emptied, the options will be used on the next restart but will be lost after that. So the next time a user restarts the wallet (for whatever reason) the options will not be used.

Example use case: a user wants to always run zend with options:
`-disabledeprecation=2.0.11 -alerts`
So the user sets them once in the GUI and restarts the wallet (so far so good). Then the user shuts down his PC for the day and starts the wallet again two days later - the options for zend will not be there any longer... unless the user sets them in the GUI again manually.

BTW: The icon `src/resources/images/advance-settings.png` is not used. If it is to remain for future use, it is a good idea to specify where it was taken from and whether it is free to use under MIT license...

**Comment by josephnicholas** [comment]
@zenportodev Noted on the points you have mentioned, the code still needs alot to refactor, and I understand your concern about emptying the _commands.conf_, and I totally agree on your point, but what happends if we add commands like, **-reindex or -rescan**? Do the user want those changes applied everytime the user restarts the application?

Another thing also, I should remove the icon, since its not being used, thanks for that.

**Comment by zenportodev** [comment]
I agree that with some options the user enters (e.g. -reindex or -rescan) the intention will be to use them only once (on the next zend restart). With other options (I think more common case) the user will expect to have them every stat of zend (e.g. -disabledeprecation=2.0.11). I would not object to having either implementation (or both) as long as it is made clear to the user how it works...

Proposal: if you wish to have the options only on the next restart (and empty the options file) once the user clicks the apply button for the options, show a "big warning" to the user to the effect that: the zend options entered will be used ONLY on the next ONE restart... not on subsequent restarts, unless the users enters them in the GUI again.

BTW: My opinion is that such an implementation is not so user-friendly but I would not object to it...

**Comment by zenportodev** [comment]
My tests with the latest version are OK. I only recommend changing the label text:

advanced

to be absolutely clear to the user that the options will be used ONLY once on the next restart, and not on subsequent restarts... without the user entering them in the GUi again.

**Comment by josephnicholas** [comment]
@zenportodev will do the changes now. But let us just place the feature where we have a checkbox where we can say that. **Run command/s on every startup** in that case the user will know that command applied are ran during startup and unchecking it will let just let it run once.

What do you think @zenportodev ?

**Comment by zenportodev** [comment]
Indeed I think having a check-box is a good idea, to let the user decide if the options are to be used only once or every subsequent restart:
```
...where we can say that. Run command/s on every startup in that case the user will know that command applied are ran during startup and unchecking it will let just let it run once.
```
Good idea...

**Comment by josephnicholas** [comment]
@zenportodev Thanks for the review. Just to formalize everything on the configuration file. I was thinking of having this format.

```
[Commands]
-disabledeprecation=2.0.11 -alerts

[Options]
RunOnce=1
```

So the commands section will have a line listing all of the applied user commands, and then the options are list of options that will be applied on the wallet/daemon, so for now we have RunOnce=1 meaning commands will only run once after restart and not on subsequent restart, default should be 1.

So we build this config during wallet startup, if file is not found we create the file and have the necessary defaults applied.

**Comment by josephnicholas** [comment]
@zenportodev did some code changes with how the configuration is implemented as well as the command recurrence. Some minor refactoring can be done on the code but I think I will do that after. If all else is good to you please approve the PR. 

Thanks.

**Comment by zenportodev** [comment]
My tests with the latest version are OK. From my point of view it is OK. Feel free to merge it.

**Comment by josephnicholas** [comment]
Thanks @zenportodev . Done with merging doing final tests with it for master branch, and editing some wording for UX purposes.

**Pull request merged**
